[font]
	normal = { family = "Liberation Mono", style = "Regular" }
	bold = { style = "Bold" }
	italic = { style = "Italic" }
	bold_italic = { style = "Bold Italic" }
	size = 11
	offset = {x= 0, y= 0}
	builtin_box_drawing = false 

[colors]
	primary = {foreground = "#cec9c9", background = "#000000", dim_foreground = "#dddddd", bright_foreground = "None"}
	cursor = {text = "#000000", cursor = "#21eb10"}

[cursor]
	style = { shape = "Beam", blinking = "Always" }
	blink_interval = 500
	blink_timeout = 0
	thickness = 0.19


[colors.normal]
    black = "#000000"
    red = "#ff0000"
    green = "#00ff00"
    yellow = "#f39207"
    blue = "#096dc1"
    magenta = "#ff00ff"
    cyan = "#00ffff"
    white = "#ffffff"

[colors.bright]
    black = "#000000"
    red = "#ff0000"
    green = "#00ff00"
    yellow = "#f39207"
    blue = "#096dc1"
    magenta = "#ff00ff"
    cyan = "#00ffff"
    white = "#ffffff"

[colors.dim]
    black = "#000000"
    red = "#ff0000"
    green = "#00ff00"
    yellow = "#f39207"
    blue = "#096dc1"
    magenta = "#ff00ff"
    cyan = "#00ffff"
    white = "#999999"


