[font]
	normal = { family = "IBM plex mono", style = "Medium" }
	bold = { style = "Bold" }
	italic = { style = "Italic" }
	bold_italic = { style = "Bold Italic" }
	size = 10
	offset = {x= 1, y= 0}
	builtin_box_drawing = true 


[colors]
	primary = {foreground = "#d8d8d8", background = "#000000", dim_foreground = "#828482", bright_foreground = "None"}
	cursor = {text = "#000000", cursor = "#1dc40c"}

[cursor]
	style = { shape = "Beam", blinking = "Always" }
	blink_interval = 500
	blink_timeout = 0
	thickness = 0.17


[colors.normal]
    black = "#000000"
    red = "#ff0000"
    green = "#00ff00"
    yellow = "#d47c02"
    blue = "#0c6bbc"
    magenta = "#ff00ff"
    cyan = "#00ffff"
    white = "#999999"

[colors.bright]
    black = "#000000"
    red = "#ff0000"
    green = "#00ff00"
    yellow = "#d47c02"
    blue = "#0c6bbc"
    magenta = "#ff00ff"
    cyan = "#00ffff"
    white = "#999999"

[colors.dim]
    black = "#000000"
    red = "#540408"
    green = "#1dc40c"
    yellow = "#d47c02"
    blue = "#0c6bbc"
    magenta = "#ff00ff"
    cyan = "#00ffff"
    white = "#999999"


