vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", ":Ex<CR>")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<leader>y", '"+y')
vim.keymap.set("v", "<leader>y", '"+y')
vim.keymap.set("n", "<leader>Y", '"+Y')
vim.keymap.set("n", "<leader>s",":%s/\\<<C-r><C-w>\\>/<C-r><C-w>/gI<Left><Left><Left>")
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("x", "<leader>dP", '"_dP')
vim.keymap.set("n", "<leader>gs", ":Git<CR>")
vim.keymap.set("n", "<leader>nl", ":nohl<CR>")
vim.keymap.set("n", "<leader>bs", ":bnext<cr>")
vim.keymap.set("n", "<leader>bS", ":bprev<cr>")
vim.keymap.set("n", "<leader>bT", ":Telescope buffers<CR>")
vim.keymap.set("n", "<leader>|", ":vsp<CR>")
vim.keymap.set("n", "<leader>-", ":sp<CR>")
